# Forces faster Travis-CI Container Infrastructure
sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # Until the next stable group update after 2016-12-01

before_script:
  - travis_retry composer require phpunit/phpunit phpbench/phpbench
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - composer test
  - composer bench

after_script:
  - bash -c '[[ -f "build/logs/clover.xml" ]] && wget https://scrutinizer-ci.com/ocular.phar'
  - bash -c '[[ -f "build/logs/clover.xml" ]] && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml'
